apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-platform-prod
resources:
  - ../../base
  - namespace.yaml
  - poddisruptionbudget.yaml
configMapGenerator:
  - name: infra-platform-api-config
    behavior: merge
    literals:
      - APP_ENV=production
      - APP_MESSAGE=configuração do ambiente de produção carregada
patches:
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/justshinobi/infra-platform-api
    digest: sha256:3004a459aa420d04735e58254973bd078866ab715c168200fd7c57a5281e8cef
