apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-platform-prod
resources:
  - ../../base
  - namespace.yaml
  - poddisruptionbudget.yaml
configMapGenerator:
  - name: infra-platform-api-config
    behavior: merge
    literals:
      - APP_ENV=production
      - APP_MESSAGE=configuração do ambiente de produção carregada
patches:
  - path: deployment-patch.yaml
images:
  - name: ghcr.io/justshinobi/infra-platform-api
    digest: sha256:332947faca13b91bdc8c3b000ceba2f69491e1bb7af8ed128cd02024de685f64
