apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: infra-platform-api-config
    literals:
      - APP_ENV=base
      - APP_MESSAGE=configuração padrão carregada
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: infra-platform-api
      app.kubernetes.io/part-of: infra-platform-api
