apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-platform-dev
resources:
  - ../../base
  - namespace.yaml
configMapGenerator:
  - name: infra-platform-api-config
    behavior: merge
    literals:
      - APP_ENV=development
      - APP_MESSAGE=configuração do ambiente de desenvolvimento carregada
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/justshinobi/infra-platform-api
    digest: sha256:f22e2c9fa6ab0a46aa761694df06b030662a2ad19d5c4bd8099b3cbcc7e422f2
