apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-platform-dev
resources:
  - ../../base
  - namespace.yaml
configMapGenerator:
  - name: infra-platform-api-config
    behavior: merge
    literals:
      - APP_ENV=development
      - APP_MESSAGE=configuração do ambiente de desenvolvimento carregada
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/justshinobi/infra-platform-api
    digest: sha256:6190134a9d3983823222a4594269e519be2f3d259794d5c71fd779a9db282e76
