apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-platform-dev
resources:
  - ../../base
  - namespace.yaml
configMapGenerator:
  - name: infra-platform-api-config
    behavior: merge
    literals:
      - APP_ENV=development
      - APP_MESSAGE=configuração do ambiente de desenvolvimento carregada
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/justshinobi/infra-platform-api
    digest: sha256:b65fe9463080bb60b984ddcd39c8e741726cec094385f21244524a04daaf6028
